"""empty message

Revision ID: 5d8c1cddf006
Revises: 26390d2d2518
Create Date: 2026-02-19 23:36:38.434020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8c1cddf006'
down_revision = '26390d2d2518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_date', sa.Date(), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment2')
    op.drop_table('loan2')
    # ### end Alembic commands ###
